# prometheus global config 
global:
  scrape_interval: 10s
  evaluation_interval: 10s 
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'zookeeper'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.204.133:7000','192.168.204.132:7000','192.168.204.134:7000']
  - job_name: 'kafka'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.204.133:7071','192.168.204.132:7071','192.168.204.134:7071']

